title: kozahq
description: "Consulting Services for Pipeline Growth"

url: "https://kozahq.com"
baseurl: ""

theme: minima

minima:
  social_links: []
  feed_show: false  # <-- this line disables the feed link (custom logic)
  skin: auto
  include_css:
    - /assets/css/style.css

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
