# remote_theme: "jekyll/minima@1e8a445"
theme: minima
title: kozahq
description: Consulting Services for Pipeline Growth

minima:
  social_links: []
  feed_show: false  # <-- this line disables the feed link (custom logic)
