baseurl: "/kozahq"
url: "https://ozer-do.github.io"

theme: minima
title: kozahq
description: Consulting Services for Pipeline Growth

minima:
  social_links: []
  feed_show: false  # <-- this line disables the feed link (custom logic)
  skin: auto
  include_css:
    - /kozahq/assets/css/custom.css

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
